### ISSUE TITLE
Make failure on macOS

### ISSUE THREAD

**Issue by steve64** [PQCraft/clibasic#6]
### Steps to reproduce:
make build

### Expected behavior:
Build clibasic executable

### Actual behavior:
Error in source code

### Screenshots:
Add screenshots or paste terminal output
```
% make build
gcc clibasic.c --std=c99 -Wall -Wextra -Ofast -lm -lreadline -I/usr/local/opt/readline/include -L/usr/local/opt/readline/lib -DB64 -o "clibasic" && chmod +x "clibasic"
clibasic.c:747:49: error: use of undeclared identifier 'size'
            if (_NSGetExecutablePath(startcmd, &size)) {
                                                ^
clibasic.c:1013:1: error: unknown type name '__sighandler_t'
__sighandler_t gcpoldsigh;
^
2 errors generated.
make: *** [build] Error 1
```

### Device info:
- **Type:** PC
- **OS:** MacOS, BigSur 11.2.3

### Additional information:
(If applicable, add more info on the problem)

**Comment by PQCraft** [comment]
It should be fixed in the testing branch now, sorry it took so long for me to see this issue :grimacing:

**Comment by PQCraft** [comment]
@steve64 It should be fixed in the testing branch now, sorry it took so long for me to see this issue :grimacing:

**Comment by steve64** [comment]
Thanks a lot. When do you expect to have the fix in the mainstream release?

**Comment by PQCraft** [comment]
@steve64 ill push these to main once im done testing and adding the new features (manpage coming soon btw), ill leave this open in the meantime in case someone else has this issue :+1:

**Comment by Thatguyonfire240** [comment]
I just tested this on my m1 MacBook running bigsur, I had 6 errors on master, down to 5 in testing, still broken on my machine lol

**Comment by PQCraft** [comment]
fixed in 0.22, closing
